# Generated by Django 5.2.5 on 2025-09-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networklink",
            name="level",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Завод"), (1, "Уровень сети №1"), (2, "Уровень сети №2")],
                editable=False,
                null=True,
                verbose_name="Уровень иерархии",
            ),
        ),
    ]
